### ISSUE TITLE
pm2 crashes immediately after launching app

### ISSUE THREAD

**Issue by ShalbafZadeh** [sadra/EasyMTProto#1]
after running ```pm2 start emtproto.js -i max``` i get this error : 
```
root@1:~/EasyMTProto# pm2 logs emtproto
[TAILING] Tailing last 15 lines for [emtproto] process (change the value with --lines option)
/root/.pm2/logs/emtproto-out-0.log last 15 lines:
/root/.pm2/logs/emtproto-error-0.log last 15 lines:
0|emtproto |     at Function.Module._load (module.js:497:3)
0|emtproto |     at Module.require (module.js:596:17)
0|emtproto |     at require (internal/module.js:11:18)
0|emtproto |     at Object.<anonymous> (/root/EasyMTProto/emtproto.js:6:21)
0|emtproto | SyntaxError: Unexpected token } in JSON at position 118
0|emtproto |     at JSON.parse (<anonymous>)
0|emtproto |     at Object.<anonymous> (/root/EasyMTProto/routes/index.js:4:21)
0|emtproto |     at Module._compile (module.js:652:30)
0|emtproto |     at Object.Module._extensions..js (module.js:663:10)
0|emtproto |     at Module.load (module.js:565:32)
0|emtproto |     at tryModuleLoad (module.js:505:12)
0|emtproto |     at Function.Module._load (module.js:497:3)
0|emtproto |     at Module.require (module.js:596:17)
0|emtproto |     at require (internal/module.js:11:18)
0|emtproto |     at Object.<anonymous> (/root/EasyMTProto/emtproto.js:6:21)
```

npm: 5.6.0
node: 8.11.2

**Comment by sadra** [comment]
Did install the dependencies with `npm install`?
try again to install packages

**Comment by sadra** [comment]
Closing this issue as it seems your problem was resolved.
